### ISSUE TITLE
[INFO] A piHole java api client lib

### ISSUE THREAD

**Issue by ppadial** [pi-hole/api#11]
Just to share, if someone is interested: 
  https://github.com/ppadial/pihole-api-client-java

Right now is a quite simple api, but i have it made to integrate with some scripts i have at home for dashboarding.

cheers

**Comment by Mcat12** [comment]
Thanks for sharing! The API has been moved to a part of FTL (see pi-hole/FTL#75), so this repo might not exist for much longer. Perhaps share to Discourse or Reddit as well?

**Comment by ppadial** [comment]
Hi, no, i didn't share it yet on these sites.

I'm updating a bit to implement all the FTL methods, so, i will track that FTL issue to update my api when is pushed.

Thank you very much !
