### ISSUE TITLE
How to install .rpm package when there is no support for rpm 

### ISSUE THREAD

**Issue by viraj1899** [pi-hole/api#135]
I am using proprietary version of centos,hence there no provision of yum install as it is my NAS server. 

[/] # yum
-sh: yum: command not found

--------------------------**Query to be asked**---------------------------

1.Is there any other way to install .rpm package when rpm is unsupported ?
2. Or How can i install rpm ?

[/] # rpm
-sh: rpm: command not found

**Comment by AzureMarker** [comment]
Contact your NAS manufacturer on how to install RPM packages. We don't have any knowledge of your system.
