### ISSUE TITLE
Document Schema

### ISSUE THREAD

**Issue by diginc** [pi-hole/api#5]
I'd be tempted to pull request some features to this if I saw a schema document detailing what was needed with example HTTP Method / URL Path / JSON payloads properties  

Here are some quick dirty examples to get the ball rolling.
> GET /log with json filters: IP origin, DNS type, block/allow (aka blacklist/whitelist), limit, order
> POST/UPDATE/DELETE /block & /allow property: domain
> POST/UPDATE/DELETE /list properties: enable true/false, url

**Comment by diginc** [comment]
```
("/codes", methods=["GET"]) 
("/dns/whitelist", methods=["GET"])
("/dns/whitelist", methods=["POST"])
("/dns/whitelist/<int:domain_id>", methods=["GET"])
("/dns/whitelist/<int:domain_id>", methods=["DELETE"])
("/dns/blacklist", methods=["GET"])
("/dns/blacklist", methods=["POST"])
("/dns/blacklist/<int:domain_id>", methods=["GET"])
("/dns/blacklist/<int:domain_id>", methods=["DELETE"])
("/dns/history", methods=["GET"])
("/dns/history/<int:from_time>/<int:until_time>")
```

Here is what you have so far it seems.  Do any of these need additions?  What are you missing and still need?  

A few things I can think of:  Authorization, ad list management, and the 'top' dashboard graph log data.

**Comment by Mcat12** [comment]
Like a swagger definition? We actually started the API by defining it in a swagger yaml. If no one else posts it by tomorrow, I'll upload it. (Getting kind of late here)

**Comment by Mcat12** [comment]
Also, since the api is a work in progress, there will be more features than are shown in the current spec. For example: we're going to implement some sort of authorization, though it's not currently defined in the swagger yaml.

**Comment by diginc** [comment]
I haven't worked with swagger-api before but as long as it portrays the end or stage 1 vision of the pihole api then that is what I was hoping to see.

I was more thinking a simple readme.md document detailing what was coming to the API so that others could provide feedback and propose new features.

**Comment by Mcat12** [comment]
Here's a version of the file. I think it's pretty up to date. I had to upload it with .txt to get Github to accept it.
[swagger.yaml](https://github.com/pi-hole/api/files/418559/swagger.yaml.txt)

**Comment by diginc** [comment]
Cool, thanks!  So now that I see the full spec I can say for certain something I had in mind probably wouldn't work with the current /history API.  I was expecting lots more filters on the history, partly so we could start having a more powerful webUI filtering system but also for browser extension usages.

> GET /log with json filters: IP origin, DNS type, block/allow (aka blacklist/whitelist), limit, order

I thought DNSQuery history based off the client (IP) and blocked would be very useful for a browser extension which reports your (and only your) recently blocked pages when you suspect that a page is being broken by pi-hole.  Having the option to whitelist right from the browser extension too would of course require some authorization layer too, but that could come later.

Having multiple history filters will quickly cause the URL only based API to break down: 
/history/range/<int>/<int> + /history/blocked/ + /history/client, how how do you combined those 3 sanely?  

Suddenly just using JSON payloads rather than URL pattern matching is easier or you end up with history/client/range/blocked URL combinations up the wazzoo.  E.G.

/history/ POST + `{ filter: { range: { start: <int>, stop: <int>} , blocked: True, client: 192.168.1.100 } }` with any of the filters being optional.

Thoughts?

**Comment by Mcat12** [comment]
We can certainly adapt the API! Those filters you mentioned would be nice to have. We'll look into the advantages/disadvantages of changing how the history endpoint operates.

Another thing to think about is moving the sorting and such to the client machine, in order to not overload the Pi-hole API. It could be hosted on something as low powered as a Pi B, so keeping the server computation down is also a factor in this API.

**Comment by diginc** [comment]
If there is a way to programmatically tell what pi hardware someone is running I'd imagine turning off the more intensive features would be easy.  Or if there were a initial setup for the web UI (good time for authorization setup too) maybe it could just poll the user to ask if they're running Pi B and want to limit cpu intensive features.

Since you answered my initial question with the swagger yaml and heard my feedback I'll go ahead and close.

**Comment by dschaper** [comment]
There actually is, Dan (of DietPi) wrote a little script that polls for information and displays, among other things, the Model and capabilities. https://raw.githubusercontent.com/Fourdee/DietPi/testing/dietpi/misc/rpi_boardinfo
