### ISSUE TITLE
Stats per resolver

### ISSUE THREAD

**Issue by michbsd** [pi-hole/api#63]
Hi,

First off, thanks for all your hard work on this project !!

Second, I have a small feature request - if would be great if I could get by resolver in the query log. 

I would like to see which lookups was sent to which resolver. 

Thanks

**Comment by AzureMarker** [comment]
I transferred this to the API repo, since the API handles these kinds of features. You should also make a feature request on the Pi-hole Discourse forums so people can vote on it.

**Comment by AzureMarker** [comment]
This may also require changes in pi-hole/FTL.

**Comment by michbsd** [comment]
Thanks. Actually the info is already available on the pihole.log. So "just" adding it to the API and the frontend.

**Comment by AzureMarker** [comment]
Nothing reads data from the log anymore. I was mostly concerned if the query data structure in FTL contained the upstream server it was forwarded to (it does).

**Comment by michbsd** [comment]
Cool! I will add a post on discourse forum as soon well. Thanks

**Comment by AzureMarker** [comment]
This is currently implemented in the `development` branch:
https://github.com/pi-hole/api/blob/b996123e9dafc9b7113c39a00ba90d5999a78934/src/routes/stats/history.rs#L377

You can filter by upstream by adding the `upstream=...` GET parameter to a `/admin/api/stats/history` request (replace `...` with the upstream IP or name, such as `8.8.8.8` or `blocklist`).

**Comment by AzureMarker** [comment]
We aren't planning on adding another column to the query log on the web interface for the upstream.

**Comment by michbsd** [comment]
Awesome. Many thanks.
