### ISSUE TITLE
Will this API replace the current AdminLTE API?

### ISSUE THREAD

**Issue by double-fault** [pi-hole/api#65]
Will this new API eventually replace the current PHP API in AdminLTE, or will they both exist?

**Comment by AzureMarker** [comment]
The new web interface will replace the old one. The old one used PHP (a server-side language) for to supply the stats, but we are removing PHP from the project. The new web interface is completely JavaScript (client-side), so it needs an API to supply its data. This API does that job. The APIs will not exist together.

**Comment by double-fault** [comment]
Alright, thanks!
