### ISSUE TITLE
Documentation overview

### ISSUE THREAD

**Issue by sterrenb** [pi-hole/api#83]
While playing around with this API on my own Pi-hole (v4.1.1), I am struggling to find documentation for the different endpoints and their options. 

Currently I am using the blogpost (https://discourse.pi-hole.net/t/pi-hole-api/1863), but this seems somewhat outdated.

Is there any place I can find up-to-date or version-based endpoint documentation?

**Comment by AzureMarker** [comment]
That blog post is for the old PHP API. This repo is for the upcoming API written in Rust. Which API are you using?

For the Rust API, the best documentation currently is the code. I do plan on adding documentation to the main docs site once we're closer to release.

**Comment by sterrenb** [comment]
I see, I am using the old PHP API for my internal testing then.

That sounds great, thank you for letting me know. I will watch the progress in the repo and await further releases.
